version: '3'
services:
  web:
    image: nginx:alpine
    container_name: webserver
    volumes:
      - ./application/dist:/usr/share/nginx/html
      - ./application/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
  # db:
  #   image: mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
